// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Birthday struct {
	ID             int64     `json:"id"`
	FullName       string    `json:"full_name"`
	FutureBirthday time.Time `json:"future_birthday"`
}
