// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Reminder struct {
	ID             int64     `json:"id"`
	FullName       string    `json:"full_name"`
	PersonalNumber int64     `json:"personal_number"`
	User           string    `json:"user"`
	PhoneNumber    string    `json:"phone_number"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PhoneNumber       string    `json:"phone_number"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
