// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateBirthday(ctx context.Context, arg CreateBirthdayParams) (Birthday, error)
	DeleteBirthday(ctx context.Context, id int64) (Birthday, error)
	GetBirthday(ctx context.Context, id int64) (Birthday, error)
	ListBirthdays(ctx context.Context, arg ListBirthdaysParams) ([]Birthday, error)
	UpdateBirthday(ctx context.Context, arg UpdateBirthdayParams) (Birthday, error)
}

var _ Querier = (*Queries)(nil)
