// Code generated by sqlc. DO NOT EDIT.
// source: sms.sql

package db

import (
	"context"
)

const getSmsReminders = `-- name: GetSmsReminders :many
SELECT id, full_name, personal_number, "user", phone_number, created_at FROM reminders
WHERE "user" = $1
ORDER BY personal_number
`

func (q *Queries) GetSmsReminders(ctx context.Context, user string) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, getSmsReminders, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PersonalNumber,
			&i.User,
			&i.PhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
