apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::364271544117:user/github-ci
      username: github-ci
      groups: 
        - system:masters